# Generated by Django 4.1.2 on 2022-10-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=50)),
                ('report_data', models.CharField(max_length=700)),
                ('date_added', models.DateField()),
            ],
        ),
    ]
