# Generated by Django 4.1.2 on 2022-10-28 13:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
